services:
  postgres:
    image: postgres:15-alpine
    container_name: daily_tutor_bot_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - daily_tutor_bot_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily_user_bot_app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - postgres
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
      STATUS_SERVER_PORT: ${STATUS_SERVER_PORT}
    ports:
      - "${STATUS_SERVER_PORT}:8080"

volumes:
  daily_tutor_bot_postgres_data:
    external: true
